<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Code/RoleManagement.aspx.cs" Inherits="RoleManagement" Trace="false" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>Role Management</title>
</head>
<body>
    <form id="form1" runat="server">
        <table border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td style="width: 150px;background-color: brown" valign="top" />
                <td style="width: 750px">
                    <table runat="server" style="width: 750px">
                        <tr>
                            <td align="left" style="color: white; height: 100px; background-color: brown">
                                <asp:LoginView ID="LoginView1" runat="server">
                                    <AnonymousTemplate>
                                        Alias not authenticated. You are not authorized to view this page.
                                    </AnonymousTemplate>
                                    <RoleGroups>
                                        <asp:RoleGroup Roles="Admin">
                                            <ContentTemplate>
                                                <h3>Authentication:</h3>
                                                <h2>Administrator</h2>
                                            </ContentTemplate>
                                        </asp:RoleGroup>
                                        <asp:RoleGroup Roles="User">
                                            <ContentTemplate>
                                                <h3>Authentication:</h3>
                                                <h2>User<h2>
                                            </ContentTemplate>
                                        </asp:RoleGroup>
                                    </RoleGroups>
                                </asp:LoginView>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <br />
                                <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="Larger" Text="Please use the selection link before you edit!" /><br /><br />
                                <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Refresh Roles"
                                    Width="205px" /><br />
                                <asp:GridView ID="GridView1" runat="server" AllowPaging="True"
                                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True"
                                BackColor="#DEBA84" BorderColor="Brown" BorderStyle="Solid" BorderWidth="5px"
                                Caption="Current Application Role List:" CaptionAlign="Left" CellPadding="0" CellSpacing="3" Font-Bold="False" Font-Overline="False"
                                Font-Strikeout="False" ForeColor="#333333"
                                OnRowEditing="GridView1_RowEditing" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"
                                PagerSettings-PageButtonCount="5" PageSize="5" OnRowDeleting="GridView1_RowDeleting" >
                                    <PagerSettings FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast"
                                    NextPageText="Next Page &gt;&gt;" PageButtonCount="5" Position="TopAndBottom"
                                    PreviousPageText=" Preivious Page &lt;&lt;" />
                                    <SelectedRowStyle BackColor="#FF8000" />
                                    <AlternatingRowStyle BackColor="WhiteSmoke" BorderColor="Black" BorderStyle="Solid" />
                                </asp:GridView>
                            </td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; font-size: 14pt; color: red">
                                <asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Size="Medium" Width="147px" style="border-left-color: gray; border-bottom-color: gray; border-top-color: gray; border-right-color: gray;" BorderStyle="Solid" BorderWidth="1px">Add User:</asp:Label>&nbsp;
                                <br />
                                <asp:TextBox ID="TextBox1" runat="server" Width="144px" ToolTip="Enter the user's alias here. Format: <alias> without brackets"></asp:TextBox>
                                <asp:CustomValidator ID="CustomValidator2" runat="server" ControlToValidate="TextBox1"
                                    ErrorMessage="Field cannot be empty." OnServerValidate="CustomValidator2_ServerValidate"
                                    ToolTip="You must enter only the person's alias." ValidateEmptyText="True" ValidationGroup="ValidationGroup1">*</asp:CustomValidator><asp:CustomValidator ID="CustomValidator1" runat="server" ControlToValidate="TextBox1" ErrorMessage="You must enter only the person's alias." OnServerValidate="CustomValidator1_ServerValidate" ToolTip="You must enter only the person's alias." ValidationGroup="ValidationGroup1" ValidateEmptyText="True">*</asp:CustomValidator><br />
                                    <asp:DropDownList ID="DropDownList1" runat="server" Width="151px" ToolTip="Select an Application Role type." >
                                        <asp:ListItem Selected="True"></asp:ListItem>
                                        <asp:ListItem>User</asp:ListItem>
                                        <asp:ListItem>Admin</asp:ListItem>
                                    </asp:DropDownList>
                                <asp:CustomValidator ID="CustomValidator3" runat="server" ControlToValidate="DropDownList1"
                                    ErrorMessage="You must select a Role Type from the list." OnServerValidate="CustomValidator3_ServerValidate"
                                    ToolTip="You must enter only the person's alias." ValidationGroup="ValidationGroup1" ValidateEmptyText="True">*</asp:CustomValidator><br />
                                    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Submit" Width="153px" ToolTip="Submit Application Role." /><br />
                                <asp:ValidationSummary ID="ValidationSummary1" runat="server" ShowMessageBox="True"
                                    ToolTip="Please fix these errors." ValidationGroup="ValidationGroup1" HeaderText="Please fix these errors:" />
                                </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>